development:
  adapter: postgresql
  encoding: unicode
  database: ads_dev
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: ads_test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: ads_prod
  username: postgres
  password: postgres